from bitstamp   import bitstamp
from fuze       import fuze
from zipzap     import zipzap
from mtgox      import mtgox
from btce       import btce
from vouchx     import vouchx
from dwolla     import dwolla
from paypal     import paypal
from acs        import acs
from bitcoin    import bitcoin
from virwox     import virwox